/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supermarket;

/**
 *
 * @author Edwin
 */
public class CategoryFormUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CategoryFormUI.class.getName());
 // --- 1. CLASS VARIABLES ---
    private MainDashboardUI parent;
    private DatabaseManager controller;
    private int selectedCategoryId = -1; // Tracks which category is clicked

    // --- 2. CONSTRUCTOR ---
    public CategoryFormUI(MainDashboardUI parent, DatabaseManager controller) {
        this.parent = parent;
        this.controller = controller;
        initComponents();
        
        // --- UI STYLING ---
        getContentPane().setBackground(new java.awt.Color(245, 247, 250));
        
        // Flatten text box
        javax.swing.border.Border flatBorder = javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)),
            javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5) 
        );
        txtName.setBorder(flatBorder);
        txtName.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        
        // Style Table
        categoryTable.setRowHeight(25);
        categoryTable.setShowGrid(true);
        categoryTable.setGridColor(new java.awt.Color(200, 200, 200));
        javax.swing.table.JTableHeader header = categoryTable.getTableHeader();
        header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        header.setBackground(new java.awt.Color(0, 102, 204));
        header.setForeground(java.awt.Color.WHITE);
        
        // Style Buttons
        applyStandardButtonStyle(btnAdd);
        applyStandardButtonStyle(btnUpdate);
        applyDangerButtonStyle(btnDelete);
        applySecondaryButtonStyle(btnClose);
        
        // Load the data immediately!
        refreshCategoryTable();
        
    } // <--- THE CONSTRUCTOR MUST PROPERLY CLOSE HERE!

    // =========================================================
    // HELPER METHODS (Must be outside the constructor)
    // =========================================================

    // --- CORE LOGIC: Refresh Table ---
    private void refreshCategoryTable() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) categoryTable.getModel();
        model.setRowCount(0); // Clear old data
        
        java.util.List<Object[]> list = controller.getAllCategories();
        for (Object[] row : list) {
            model.addRow(row);
        }
        
        // Reset the form
        txtName.setText("");
        selectedCategoryId = -1;
    }

    // --- HELPER METHODS FOR BUTTON STYLES ---
    private void applyStandardButtonStyle(javax.swing.JButton btn) {
        btn.setBackground(new java.awt.Color(0, 102, 204)); 
        btn.setForeground(java.awt.Color.WHITE);
        btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        btn.setFocusPainted(false); btn.setBorderPainted(false);
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }

    private void applyDangerButtonStyle(javax.swing.JButton btn) {
        btn.setBackground(new java.awt.Color(220, 53, 69)); 
        btn.setForeground(java.awt.Color.WHITE);
        btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        btn.setFocusPainted(false); btn.setBorderPainted(false);
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }

    private void applySecondaryButtonStyle(javax.swing.JButton btn) {
        btn.setBackground(new java.awt.Color(108, 117, 125)); 
        btn.setForeground(java.awt.Color.WHITE);
        btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        btn.setFocusPainted(false); btn.setBorderPainted(false);
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        categoryTable = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Category");

        jLabel1.setText("New Category Name:");

        categoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Category Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        categoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoryTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(categoryTable);

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnClose.setText("Close");
        btnClose.addActionListener(this::btnCloseActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    String name = txtName.getText().trim();
    if (!name.isEmpty()) {
        if (controller.addCategory(name)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Category Added!");
            refreshCategoryTable();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error adding category.");
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void categoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryTableMouseClicked
    int selectedRow = categoryTable.getSelectedRow();
    if (selectedRow >= 0) {
        selectedCategoryId = (int) categoryTable.getValueAt(selectedRow, 0);
        txtName.setText(categoryTable.getValueAt(selectedRow, 1).toString());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_categoryTableMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
    String name = txtName.getText().trim();
    if (selectedCategoryId != -1 && !name.isEmpty()) {
        if (controller.updateCategory(selectedCategoryId, name)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Category Updated!");
            refreshCategoryTable();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error updating category.");
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a category from the table first.");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    if (selectedCategoryId != -1) {
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this category?", "Warning", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            if (controller.deleteCategory(selectedCategoryId)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Category Deleted!");
                refreshCategoryTable();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Cannot delete category (It might be in use by products!).");
            }
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a category to delete.");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTable categoryTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
