/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supermarket;

import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class Form extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form.class.getName());

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        lblRevenue = new javax.swing.JLabel();
        lblExpenses = new javax.swing.JLabel();
        lblMargin = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTargetID = new javax.swing.JTextField();
        txtNewThreshold = new javax.swing.JTextField();
        btnSaveThreshold = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        cmbApplyTo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Refresh Stock");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Stock Monitor", jPanel1);

        jButton2.setText("Generate Latest Report");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(183, 183, 183))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sales Reports", jPanel3);

        lblRevenue.setText("Total Revenue: RM0.00");

        lblExpenses.setText("Total Expenses: RM0.00");

        lblMargin.setText("Net Profit Margin: RM0.00");

        jButton4.setText("Calculate Profit Metrics");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMargin)
                            .addComponent(lblExpenses)
                            .addComponent(lblRevenue)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jButton4)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jButton4)
                .addGap(32, 32, 32)
                .addComponent(lblRevenue)
                .addGap(33, 33, 33)
                .addComponent(lblExpenses)
                .addGap(39, 39, 39)
                .addComponent(lblMargin)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Profit Analysis", jPanel4);

        jLabel1.setText("Product/Category ID:");

        jLabel2.setText("New Minimum Quantity:");

        btnSaveThreshold.setText("Save Changes");
        btnSaveThreshold.addActionListener(this::btnSaveThresholdActionPerformed);

        cmbApplyTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single Product ID", "Entire Category ID" }));
        cmbApplyTo.addActionListener(this::cmbApplyToActionPerformed);

        jLabel3.setText("Apply to:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTargetID, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtNewThreshold)
                            .addComponent(cmbApplyTo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(lblMessage))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(btnSaveThreshold)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbApplyTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTargetID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNewThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnSaveThreshold)
                .addGap(53, 53, 53)
                .addComponent(lblMessage)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Threshold Config", jPanel2);

        btnClose.setText("Close");
        btnClose.addActionListener(this::btnCloseActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(248, 248, 248))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

   // 1. Point to your friend's newly fixed controller
        StockController controller = new StockController();
        
        // 2. Let the controller do all the hard work of fetching and formatting the data
        javax.swing.table.DefaultTableModel model = controller.getStockTableModel();
        
        // 3. Inject the perfect data into the table
        jTable1.setModel(model);
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSaveThresholdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveThresholdActionPerformed
// 1. Get the inputs from your UI
        // Change 'cmbApplyTo', 'txtTargetID', and 'txtNewThreshold' to match your actual variable names!
        String updateType = cmbApplyTo.getSelectedItem().toString();
        String targetIdStr = txtTargetID.getText().trim();
        String qtyStr = txtNewThreshold.getText().trim();

        // 2. EXCEPTION FLOW & CONSTRAINTS: Validate the input
        try {
            int targetId = Integer.parseInt(targetIdStr);
            int newQty = Integer.parseInt(qtyStr);

            // Constraint: Must be a positive integer
            if (newQty < 0) {
                JOptionPane.showMessageDialog(this, "Invalid Input: Threshold cannot be negative.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return; // Stops the process
            }

            // 3. Determine if this is a Category Bulk Update or Single Product
            boolean isCategory = updateType.equals("Entire Category ID");

            // 4. Send to Database
            DatabaseManager db = new DatabaseManager();
            boolean success = db.updateLowStockThreshold(isCategory, targetId, newQty);

            if (success) {
                JOptionPane.showMessageDialog(this, "Thresholds successfully updated!", "Success", JOptionPane.INFORMATION_MESSAGE);
                // Clear the fields after success
                txtTargetID.setText("");
                txtNewThreshold.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Update failed. Please check if the ID exists.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException ex) {
            // Exception Flow: Triggers if they type text (like "abc") instead of a number
            JOptionPane.showMessageDialog(this, "Invalid Input: Please enter valid whole numbers only.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }  // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveThresholdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 // 1. Connect to your database
    DatabaseManager db = new DatabaseManager();
    
    // 2. Fetch the report text using the method we just added
    String reportData = db.getLatestSalesReport();
    
    // 3. Display it in the large white box!
    // IMPORTANT: Change 'jTextArea1' if your white box has a different variable name.
    jTextArea1.setText(reportData);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    // 1. Fetch the calculated numbers from the database
        DatabaseManager db = new DatabaseManager();
        double[] data = db.getProfitAnalysisData();

        // 2. Format the numbers to 2 decimal places
        String revenueStr = String.format("RM %.2f", data[0]);
        String expensesStr = String.format("RM %.2f", data[1]);
        String profitStr = String.format("RM %.2f", data[2]);
        String marginStr = String.format("%.2f %%", data[3]);

        // 3. Update the labels on your screen!
        // (Make sure to use the exact variable names you set in Step 2)
        lblRevenue.setText("Total Revenue: " + revenueStr);
        lblExpenses.setText("Total Expenses: " + expensesStr);
        
        // Let's make the margin label show the actual profit amount AND the percentage
        lblMargin.setText("Net Profit: " + profitStr + " (Margin: " + marginStr + ")");
        
        // Optional: Make it green if you are making money, red if losing money
        if (data[2] >= 0) {
            lblMargin.setForeground(new java.awt.Color(34, 139, 34)); // Green
        } else {
            lblMargin.setForeground(java.awt.Color.RED);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cmbApplyToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbApplyToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbApplyToActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new Form().setVisible(true));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSaveThreshold;
    private javax.swing.JComboBox<String> cmbApplyTo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblExpenses;
    private javax.swing.JLabel lblMargin;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblRevenue;
    private javax.swing.JTextField txtNewThreshold;
    private javax.swing.JTextField txtTargetID;
    // End of variables declaration//GEN-END:variables
}
