/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supermarket;

/**
 *
 * @author Edwin
 */
public class ProductFormUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProductFormUI.class.getName());
    // --- 1. CLASS VARIABLES ---
    private MainDashboardUI parent;
    private DatabaseManager controller;
    private boolean isUpdateMode = false;
    private int currentProductId = -1;

    // --- HELPER: Standard Blue Button ---
    private void applyStandardButtonStyle(javax.swing.JButton btn) {
        btn.setBackground(new java.awt.Color(0, 102, 204)); 
        btn.setForeground(java.awt.Color.WHITE);
        btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        btn.setFocusPainted(false);
        btn.setBorderPainted(false);
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    
       
        // Smooth hover animation
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn.setBackground(new java.awt.Color(0, 76, 153)); 
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn.setBackground(new java.awt.Color(0, 102, 204)); 
            }
        });
    }
    
    // --- HELPER: Secondary Gray Button ---
    private void applySecondaryButtonStyle(javax.swing.JButton btn) {
        btn.setBackground(new java.awt.Color(108, 117, 125)); 
        btn.setForeground(java.awt.Color.WHITE);
        btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        btn.setFocusPainted(false);
        btn.setBorderPainted(false);
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        
        // Smooth hover animation
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn.setBackground(new java.awt.Color(90, 98, 104)); // Darker gray
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn.setBackground(new java.awt.Color(108, 117, 125)); // Normal gray
            }
        });
    }
    
    // --- 2. CONSTRUCTOR 1: ADD MODE (Blank Form) ---
    public ProductFormUI(MainDashboardUI parent, DatabaseManager controller) {
        this.parent = parent;
        this.controller = controller;
        initComponents();
        
        // --- STYLE THE ADD FORM ---
        getContentPane().setBackground(new java.awt.Color(245, 247, 250));
        javax.swing.border.Border flatBorder = javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)),
            javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5) 
        );
        txtName.setBorder(flatBorder);
        txtPrice.setBorder(flatBorder);
        txtStock.setBorder(flatBorder);
        txtCatId.setBorder(flatBorder);
        applyStandardButtonStyle(btnCancel); // The blue save button
    }

    // --- 3. CONSTRUCTOR 2: UPDATE MODE (Pre-filled Form) ---
    public ProductFormUI(MainDashboardUI parent, DatabaseManager controller, Product existingProduct) {
        this.parent = parent;
        this.controller = controller;
        initComponents();
        
        // --- 1. SET THE STATE ---
        this.isUpdateMode = true;
        this.currentProductId = existingProduct.getProductID();
        
        // --- 2. PRE-FILL THE TEXT BOXES ---
        txtName.setText(existingProduct.getProductName());
        txtPrice.setText(String.valueOf(existingProduct.getPrice()));
        txtStock.setText(String.valueOf(existingProduct.getStockQuantity()));
        txtCatId.setText(String.valueOf(existingProduct.getCategoryID()));
        
        // --- 3. STYLE THE UPDATE FORM ---
        getContentPane().setBackground(new java.awt.Color(245, 247, 250));
        javax.swing.border.Border flatBorder = javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)),
            javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5) 
        );
        txtName.setBorder(flatBorder);
        txtPrice.setBorder(flatBorder);
        txtStock.setBorder(flatBorder);
        txtCatId.setBorder(flatBorder);
        applyStandardButtonStyle(btnCancel); // The blue save button
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtCatId = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSave1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Product Form");

        jLabel1.setText("Product Name:");

        jLabel2.setText("Price (RM):");

        jLabel3.setText("Stock Quantity:");

        jLabel4.setText("Category ID:");

        txtStock.addActionListener(this::txtStockActionPerformed);

        txtCatId.addActionListener(this::txtCatIdActionPerformed);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        btnSave1.setText("Save");
        btnSave1.addActionListener(this::btnSave1ActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Add Inventory");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName)
                                    .addComponent(txtPrice)
                                    .addComponent(txtStock)
                                    .addComponent(txtCatId, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCatId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(301, 301, 301))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActionPerformed

    private void txtCatIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCatIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCatIdActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
  // Closes this pop-up form immediately without saving
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
    try {
            String name = txtName.getText().trim();
            double price = Double.parseDouble(txtPrice.getText().trim());
            int stock = Integer.parseInt(txtStock.getText().trim());
            int catId = Integer.parseInt(txtCatId.getText().trim());

            if (name.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Name cannot be empty!");
                return;
            }

            // --- FACTORY PATTERN & STATE CHECK ---
            boolean success = false;
            
            if (isUpdateMode) {
                // UPDATE MODE: Rebuild the existing object using Machine 2
                Product updatedProduct = ProductFactory.buildExistingProduct(currentProductId, name, price, stock, catId);
                success = controller.updateProduct(updatedProduct);
            } else {
                // ADD MODE: Build a brand new object using Machine 1
                Product newProduct = ProductFactory.createNewProduct(name, price, stock, catId);
                
                // --- TEST YOUR POLYMORPHISM ---
                System.out.println("Object Created: " + newProduct.getItemType());
                System.out.println("Total Inventory Value: RM " + newProduct.calculateTotalValue());
                
                success = controller.addProduct(newProduct);
            }
            // -------------------------------------

            // --- THE MISSING MAGIC: WHAT HAPPENS AFTER WE SAVE? ---
            if (success) {
                // 1. Show a success pop-up based on the mode
                if (isUpdateMode) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Product Updated Successfully!");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "New Product Added Successfully!");
                }
                
                // 2. Destroy this pop-up form to return to the Dashboard
                this.dispose(); 
                
            } else {
                // If the database blocked the save (e.g., wrong Category ID)
                javax.swing.JOptionPane.showMessageDialog(this, "Database Error: Failed to save product. Ensure Category ID exists.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Please enter valid numbers for Price, Stock, and Category ID.");
        }      // TODO add your handling code here:
    }//GEN-LAST:event_btnSave1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCatId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
