/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supermarket;

/**
 *
 * @author Edwin
 */
public class SystemMainMenuUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SystemMainMenuUI.class.getName());
    private DatabaseManager controller;
    /**
     * Creates new form SystemMainMenuUI
     */
    // Upgraded Constructor to accept the database connection
 // Upgraded Constructor with UI Styling
    public SystemMainMenuUI(DatabaseManager ctrl) {
        this.controller = ctrl;
        initComponents();
        
        // --- 1. STYLE THE MAIN BACKGROUND ---
        // Sets a very clean, modern light-gray/off-white background
        getContentPane().setBackground(new java.awt.Color(245, 247, 250));
        
        // --- 2. STYLE THE TITLE ---
        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 26));
        jLabel1.setForeground(new java.awt.Color(33, 37, 41)); // Sleek dark charcoal text
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        // --- 3. APPLY STYLES TO ALL MENU BUTTONS ---
        applyButtonStyle(btnProduct1);
        applyButtonStyle(btnSupplier1);
        applyButtonStyle(btnSales1);
        applyButtonStyle(btnReports);
    }

    // --- HELPER METHOD: Creates a Scale-5 Commercial Button ---
    private void applyButtonStyle(javax.swing.JButton btn) {
        // Matches the exact vibrant blue from your LoginUI
        btn.setBackground(new java.awt.Color(0, 102, 204)); 
        btn.setForeground(java.awt.Color.WHITE);
        btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        
        // --- 4. STYLE THE LOG OUT BUTTON ---
        // Using a sleek 'Danger Red' to separate it from the main navigation
        btnLogOut.setBackground(new java.awt.Color(220, 53, 69)); 
        btnLogOut.setForeground(java.awt.Color.WHITE);
        btnLogOut.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        
        btnLogOut.setFocusPainted(false);
        btnLogOut.setBorderPainted(false);
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        
        // Hover animation for the Log Out button
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogOut.setBackground(new java.awt.Color(200, 35, 51)); // Darker red on hover
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogOut.setBackground(new java.awt.Color(220, 53, 69)); // Normal red
            }
        });
        
        // Flatten the design
        btn.setFocusPainted(false);
        btn.setBorderPainted(false);
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        
        // Add the smooth hover animation
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn.setBackground(new java.awt.Color(0, 76, 153)); // Darkens on hover
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn.setBackground(new java.awt.Color(0, 102, 204)); // Returns to normal
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnReports = new javax.swing.JButton();
        btnProduct1 = new javax.swing.JButton();
        btnSupplier1 = new javax.swing.JButton();
        btnSales1 = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Supermarket POS - Main Menu");

        btnReports.setText("Reports & Analytics");
        btnReports.addActionListener(this::btnReportsActionPerformed);

        btnProduct1.setText("Product Management");
        btnProduct1.addActionListener(this::btnProduct1ActionPerformed);

        btnSupplier1.setText("Supplier Management");
        btnSupplier1.addActionListener(this::btnSupplier1ActionPerformed);

        btnSales1.setText("Sales & Orders");
        btnSales1.addActionListener(this::btnSales1ActionPerformed);

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(this::btnLogOutActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnProduct1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSupplier1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(btnSales1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(btnProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSupplier1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSales1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSales1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSales1ActionPerformed
    // 1. Create a new instance of your friend's Sales window
        SalesGUI salesWindow = new SalesGUI();
        
        // 2. Make it pop up on the screen
        salesWindow.setVisible(true);
        
        // 3. (Optional) Center the new window on the screen for a cleaner look
        salesWindow.setLocationRelativeTo(null);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSales1ActionPerformed

    private void btnProduct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct1ActionPerformed
    // Open your existing Product module and pass the database connection!
        new MainDashboardUI(controller).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnProduct1ActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // 1. Spawn a brand new Login screen
        new LoginUI().setVisible(true);
        
        // 2. Destroy this current Main Menu window to secure the session
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
    // 1. Create a new instance of your friend's Form window
        Form reportsWindow = new Form();
        
        // 2. Make it visible on the screen
        reportsWindow.setVisible(true);
        
        // 3. (Optional) Close the main menu so the screen doesn't get cluttered
        // Remove the two slashes on the next line if you want the main menu to disappear
        // this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnSupplier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplier1ActionPerformed
    // SECURITY UPGRADE: Suppliers must login before they can manage products
    // This blocks unauthorized access to the portal!
    LoginSystem loginWindow = new LoginSystem();
    loginWindow.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSupplier1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnProduct1;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnSales1;
    private javax.swing.JButton btnSupplier1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
